version: '3'

services:
  user:
    build: .
    container_name: sc_user
    ports:
      - "172.17.0.1:8081:8080"
    volumes:
     - /root/home/apps/logs:/logs

networks:
  default:
    external:
      name: sc-network