spring:
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
  cache:
    type: NONE
# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
# Upload
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
  file: /logs/app.log

bonecp:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.1.18:3306/sharingcraftsmanuser?useUnicode=yes&characterEncoding=UTF-8
  username: root
  password: root
  idleMaxAgeInMinutes: 240
  idleConnectionTestPeriodInMinutes: 60
  maxConnectionsPerPartition: 10
  minConnectionsPerPartition: 1
  partitionCount: 2
  acquireIncrement: 5
  statementsCacheSize: 100

upload:
  path: upload-dir
  extensions:
    authorized: jpeg,jpg,png

# Liquibase
#liquibase:
#  change-log: classpath:db/changelog/db.changelog-master.json