# Keep the connection alive if idle for a long time (needed in production)
spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE}
  application:
    name: sharing-craftsman-user

status:
  toinitialize: ${TO_INITIALIZE}
