# Spring
spring:
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
    initialize: false
  cache:
    type: NONE

# Logging
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
#  file: /logs/app.log

# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

bonecp:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useUnicode=yes&characterEncoding=UTF-8
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  idleMaxAgeInMinutes: 240
  idleConnectionTestPeriodInMinutes: 60
  maxConnectionsPerPartition: 10
  minConnectionsPerPartition: 1
  partitionCount: 2
  acquireIncrement: 5
  statementsCacheSize: 100