ALTER TABLE users ADD COLUMN email VARCHAR(255);
ALTER TABLE users ADD COLUMN website VARCHAR(255);
ALTER TABLE users ADD COLUMN github VARCHAR(255);
ALTER TABLE users ADD COLUMN linkedin VARCHAR(255)